-- ERALIS: categorias de produtos
-- Execute no SQL Editor do projeto Supabase ANTES de publicar esta versão.

create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.product_categories (name, sort_order, active)
select 'Produtos', 0, true
where not exists (
  select 1 from public.product_categories where lower(name) = lower('Produtos')
);

alter table public.products
  add column if not exists category_id bigint references public.product_categories(id) on delete set null;

update public.products
set category_id = (select id from public.product_categories where lower(name) = lower('Produtos') limit 1)
where category_id is null;

create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_product_categories_sort_order on public.product_categories(sort_order, created_at);

-- Leitura pública das categorias ativas.
grant select on public.product_categories to anon, authenticated;

-- O painel administrativo usa o usuário autenticado.
grant select, insert, update, delete on public.product_categories to authenticated;

alter table public.product_categories enable row level security;

-- Recriar apenas se ainda não existirem.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='product_categories' and policyname='Public can read active product categories'
  ) then
    create policy "Public can read active product categories"
      on public.product_categories for select
      to anon, authenticated
      using (active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='product_categories' and policyname='Authenticated can manage product categories'
  ) then
    create policy "Authenticated can manage product categories"
      on public.product_categories for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
