-- ERALIS / Supabase
-- Execute este script no SQL Editor do seu projeto Supabase.
--
-- Antes de executar:
-- 1. Authentication > Users: crie o usuário administrador.
-- 2. Storage: o script abaixo cria o bucket público "eralis-images".
--
-- O bucket é público apenas para leitura das imagens do catálogo.
-- Escrita/alteração/exclusão exige usuário autenticado.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(12,2) not null default 0,
  payment_url text,
  image_url text,
  image_path text,
  image_url_2 text,
  image_path_2 text,
  video_url text,
  video_path text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.idea_images (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  image_path text,
  active boolean not null default true,
  sort_order integer not null default 0,
  mobile_only boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.idea_images enable row level security;

-- Público pode somente ler conteúdo ativo.
drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
on public.products for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read active ideas" on public.idea_images;
create policy "Public can read active ideas"
on public.idea_images for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins can manage ideas" on public.idea_images;
create policy "Admins can manage ideas"
on public.idea_images for all
to authenticated
using (true)
with check (true);

grant select on public.products to anon, authenticated;
grant select on public.idea_images to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant insert, update, delete on public.idea_images to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;
grant usage, select on sequence public.idea_images_id_seq to authenticated;

-- Atualização automática de updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists idea_images_set_updated_at on public.idea_images;
create trigger idea_images_set_updated_at
before update on public.idea_images
for each row execute function public.set_updated_at();

-- Bucket público para as imagens que serão exibidas no site.
insert into storage.buckets (id, name, public)
values ('eralis-images', 'eralis-images', true)
on conflict (id) do update set public = true;

-- Leitura pública.
drop policy if exists "Public can read ERALIS images" on storage.objects;
create policy "Public can read ERALIS images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'eralis-images');

-- Upload somente para usuários autenticados.
drop policy if exists "Authenticated can upload ERALIS images" on storage.objects;
create policy "Authenticated can upload ERALIS images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'eralis-images');

-- Alteração/exclusão somente para usuários autenticados.
drop policy if exists "Authenticated can update ERALIS images" on storage.objects;
create policy "Authenticated can update ERALIS images"
on storage.objects for update
to authenticated
using (bucket_id = 'eralis-images')
with check (bucket_id = 'eralis-images');

drop policy if exists "Authenticated can delete ERALIS images" on storage.objects;
create policy "Authenticated can delete ERALIS images"
on storage.objects for delete
to authenticated
using (bucket_id = 'eralis-images');

-- Índices úteis.
create index if not exists products_active_sort_idx
on public.products (active, sort_order);

create index if not exists ideas_active_sort_idx
on public.idea_images (active, sort_order);


-- Migração para produtos com até 2 imagens e 1 vídeo.
alter table public.products add column if not exists image_url_2 text;
alter table public.products add column if not exists image_path_2 text;
alter table public.products add column if not exists video_url text;
alter table public.products add column if not exists video_path text;

-- Imagens exclusivas para celular no carrossel Criamos ideias.
alter table public.idea_images add column if not exists mobile_only boolean not null default false;
